<a href="https://colab.research.google.com/github/Pawan-KS/ML-Library-1/blob/master/Decision_Tree_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math
%matplotlib inline

In [0]:
from pks_ml_lib import convert_data
from pks_ml_lib import decision_tree

In [0]:
d_t= pd.read_csv('sample_data/mnist_test.csv',header=None)
data_t=np.array(d_t)

In [13]:
d= pd.read_csv('sample_data/mnist_train_small.csv',header=None)
data=np.array(d)
print(data)

[[6 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]
 ...
 [2 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]


In [0]:
data= convert_data(data,concerned_class=0,threshold=10)   # training and building tree
obj=decision_tree(data[:100,:])
tree= obj.build_tree(data[:100,:])    

In [18]:
print(tree)                                             # printing tree

{436: {0: {353: {0: {440: {0: {326: {0: 1, 1: 0}}, 1: 0}}, 1: 1}}, 1: 1}}


In [19]:
data_t=convert_data(data_t,concerned_class=0,threshold=10)                        # accuracy of prediction
obj.test(data_t,tree)

94.75
