<a href="https://colab.research.google.com/github/Pawan-KS/ML-Library-1/blob/master/K_Means_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math
%matplotlib inline

In [0]:
from k_clustering import k_means

In [3]:
d= pd.read_csv('sample_data/mnist_train_small.csv',header=None)
data=np.array(d)
print (data)
Y = data[:,0]
print (Y)
X = data[:,1:]
print (X)

[[6 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]
 ...
 [2 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]
[6 5 7 ... 2 9 5]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
obj=k_means()     # creating object

In [0]:
obj.train(X[:100,:],Y[:100],100,10)           # training

In [8]:
d_n = pd.read_csv('sample_data/mnist_test.csv',header=None)   # testing
data_n = np.array(d_n)
Y_n = data_n[:,0]
X_n = data_n[:,1:]

pred = obj.test(X_n[:100,:],Y_n[:100])
obj.accuracy()

15.0
