<a href="https://colab.research.google.com/github/Pawan-Kumar-Sahu/ML-Library-1/blob/master/K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math
%matplotlib inline

In [2]:
d= pd.read_csv('sample_data/mnist_train_small.csv',header=None)
data=np.array(d)
print (data)
Y = data[:,0]
print (Y)
X = data[:,1:]
print (X)

[[6 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]
 ...
 [2 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]
[6 5 7 ... 2 9 5]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
class k_means():
  def initialize(self):
    self.cent_index=np.zeros(self.k)
    self.cent_x=[]
    self.cent_y=[]
    for i in range(self.k):
      self.cent_index[i]=random.randint(0,self.m-1)
      self.cent_x.append(self.x[int(self.cent_index[i])])
      self.cent_y.append(self.y[int(self.cent_index[i])])
    self.cent_x=np.array(self.cent_x)
    self.cent_y=np.array(self.cent_y)
  
  def distance(self,xc):
    dist=np.sqrt(np.sum(pow(self.cent_x-xc,2),axis=1))
    cent_no=np.argmin(dist)
    label=self.cent_y[cent_no]
    return label,cent_no

  def train(self,x,y,itr,k):
    self.x=x
    self.y=y
    self.itr=itr
    self.k=k
    self.m=self.x.shape[0]
    self.n=self.x.shape[1]
    t=0
    self.initialize()
    while t <self.itr:
      self.label_array=[]
      centroid_list=[]
      for j in range(self.k):
        centroid_list.append(np.array([]))
      centroid_list=np.array(centroid_list)
      for i in range(self.m):
        l,c=self.distance(self.x[i])
        centroid_list[c]=np.append(centroid_list[c],i)
        self.label_array.append(l)
      for i in range(self.k):
        d=[]
        for j in centroid_list[i]:
          d.append(self.x[j])
        d=np.array(d)
        self.cent_x[i]=np.mean(d,axis=0)
      t=t+1
    print((np.count_nonzero((np.array(self.label_array)-self.y)==0)/len(self.y))*100)
  
  def accuracy(self):
    print((np.count_nonzero((self.yt-self.pred)==0)/len(self.yt))*100)

  def test(self,xt,yt):
    self.yt=yt
    self.pred=[]
    for i in range(xt.shape[0]):
       l,c=self.distance(xt[i])
       self.pred.append(l)
    return np.array(self.pred)


obj=k_means()
obj.train(X,Y,60,10)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


11.215


In [21]:
d_n = pd.read_csv('sample_data/mnist_test.csv',header=None)
data_n = np.array(d_n)
Y_n = data_n[:,0]
X_n = data_n[:,1:]

print(obj.test(X_n,Y_n))
obj.accuracy()

[1 1 1 ... 1 1 1]
11.35
