<a href="https://colab.research.google.com/github/Pawan-Kumar-Sahu/ML-Library-1/blob/master/Neural_N_Layered.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math
%matplotlib inline

In [0]:
d= pd.read_csv('mnist_train_small.csv',header=None)
data=np.array(d)
print (data)
Y = data[:,0]
print (Y)
X = data[:,1:]
print (X)

[[6 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]
 ...
 [2 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]
[6 5 7 ... 2 9 5]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
class neural():
  def sigmoid(self,c):
    return 1/(1+np.exp(-c))
  
  def create_a(self,ar,i):
    z=self.theta[i].dot(ar)
    z=np.array(self.sigmoid(z))
    if i!=self.hl:
      z=np.append(z,1)
    return z
  
  def for_prop(self):
    self.a_2d=[]
    self.a_2d.append(self.x)
    for i in range(self.hl+1):
      self.a_2d.append(self.create_a(np.array(self.a_2d)[i],i))

  def initialize(self):
    self.hl=int(input("no. of hidden layers"))
    self.n_hl=np.array([])
    self.theta=[]
    for i in range(self.hl):
      print("for hidden layer",i+1)
      self.n_hl=np.append(self.n_hl,int(input(" tell no. of nodes")))
      if i==0:
        self.theta.append(np.zeros((int(self.n_hl[i]),int(self.n))))
      if i!=0:
        self.theta.append(np.zeros((int(self.n_hl[i]),int(self.n_hl[i-1]+1))))
    self.theta.append(np.zeros((len(np.unique(self.y_all)),int(self.n_hl[-1]+1))))
    self.theta=np.array(self.theta)

  def backprop(self):
    sigma=[]
    sigma.append(self.a_2d[-1]-self.y)
    for i in range(self.hl):
      sigma.append(self.theta[-i-1].T.dot(sigma[i])*self.a_2d[-i-2]*(1-self.a_2d[-i-2]))
      #sigma=np.array(sigma)
    sigma=np.flipud(np.array(sigma))
    return sigma
  
  def y_det(self,yy):
    for index,i in enumerate(np.unique(self.y_all)):
      if yy==i:
        yy=np.zeros(len(np.unique(self.y_all)))
        yy[index]=1
        return yy
  
  def accuracy(self):
    accu=self.yt-self.pred
    print((np.count_nonzero(accu==0)/len(self.yt))*100)

  def train(self,x,y,itr=50,lr=0.00001):
    self.x_all=x
    self.y_all=y
    self.n=self.x_all.shape[1]
    self.m=self.x_all.shape[0]
    self.itr=itr
    self.lr=lr
    self.initialize()
    ref=self.theta.copy()
    k=0
    while k<self.itr+1:  
      self.delta=ref.copy()
      for i in range(self.m):
        self.x=self.x_all[i].copy()
        self.y=self.y_det(self.y_all[i].copy())
        self.for_prop()
        s=self.backprop()
        d=[]
        for l in range(self.hl+1):
          if l!=self.hl:
            a_s=np.array([self.a_2d[l]])*np.array([s[l][1:]]).T
          if l==self.hl:
            a_s=np.array([self.a_2d[l]])*np.array([s[l]]).T
          d.append(a_s)
        d=np.array(d)
        self.delta=self.delta + d
      self.delta=(1/self.m)*self.delta
      self.theta=self.theta-self.lr*self.delta
      k=k+1
    
  def test(self,xt,yt):
    self.yt=yt
    self.pred=np.array([])
    for i in range(xt.shape[0]):
      self.x=xt[i]
      self.for_prop()
      self.pred=np.append(self.pred,np.unique(self.y_all)[np.argmax(self.a_2d[-1])])
      print(self.a_2d[-1])
    return self.pred

 

obj=neural()
obj.train(X[2:4,:],Y[2:4],50,0.00001)

no. of hidden layers1
for hidden layer 1
 tell no. of nodes3


In [0]:
print(obj.test(X[2:4,:],Y[2:4]))
obj.accuracy()

[0.5 0.5]
[0.5 0.5]
[7. 7.]
50.0


In [0]:
d_n= pd.read_csv('mnist_test.csv',header=None)
data_n=np.array(d_n)
Y_n = data_n[:10,0]
print (Y_n)
X_n = data_n[:10,1:]

obj2=neural()
print(obj2.test(X_n,Y_n))
obj2.accuracy()